server:
 port: 8080


spring:
 datasource:
  url: jdbc:mysql://localhost:3306/userlayoutdb
  username: root
  password: IBmysql@1234
  driver-class-name: com.mysql.cj.jdbc.Driver


jpa:
 show-sql: true
 hibernate:
  ddl-auto: update
 database-platform: org.hibernate.dialect.MySQL8Dialect
